<?xml version="1.0"?>
<robot name="robot_arm" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="properties.xacro" />
    <xacro:include filename="macros.xacro" />

    <link name="world"/>

    <!-- Fixxed base section -->
    <joint name="base_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="world"/>
        <child link="base_link"/>
    </joint>

    <link name="base_link">
        <visual>
            <origin xyz="0 0 ${properties['base']['height'] / 2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${properties['base']['diameter'] / 2}" length="${properties['base']['height']}"/>
            </geometry>
            <material name="silver"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${properties['base']['height'] / 2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${properties['base']['diameter'] / 2}" length="${properties['base']['height']}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${properties['base']['mass']}" length="${properties['base']['height']}" radius="${properties['base']['diameter'] / 2}">
            <orgin xyz="0 0 ${properties['base']['height'] / 2}" rpy="0 0 0" />
        </xacro:inertial_cylinder>
    </link>

    <!-- Rotary torso plate joint to base -->
    <joint name="torso_joint" type="revolute">
        <origin xyz="0 0 ${properties['base']['height'] + 0.01}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="plate_link"/>
        <axis xyz="0 0 1"/>
        <limit lower="${properties['torso']['lower_limit']}" upper="${properties['torso']['upper_limit']}" velocity="100" effort="100"/> 
        <dynamics damping="10.0" friction="10.0" />
    </joint>

    <link name="plate_link">
        <visual>
            <origin xyz="0 0 ${properties['torso']['plate_height'] / 2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${properties['torso']['diameter'] / 2}" length="${properties['torso']['plate_height']}"/>
            </geometry>
            <material name="silver"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${properties['torso']['plate_height'] / 2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${properties['torso']['diameter'] / 2}" length="${properties['torso']['plate_height']}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${properties['torso']['mass']}" length="${properties['torso']['plate_height']}" radius="${properties['torso']['diameter'] / 2}">
            <origin xyz="0 0 ${properties['torso']['plate_height'] / 2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Right torso side for sholder cross member -->
    <joint name="right_torso_side_joint" type="fixed">
        <origin xyz="-${properties['torso']['side']['offset']} 0 0" rpy="0 0 0"/>
        <parent link="plate_link"/>
        <child link="right_side_link"/>
    </joint>

    <link name="right_side_link">
        <visual>
            <origin xyz="0 0 ${properties['torso']['side']['height'] / 2}" rpy="0 0 0"/>
            <geometry>
                <box size="${properties['torso']['side']['width']} ${properties['torso']['side']['length']} ${properties['torso']['side']['height']}"/>
            </geometry>
            <material name="silver" />
        </visual>
        <collision>
            <origin xyz="0 0 ${properties['torso']['side']['height'] / 2}" rpy="0 0 0"/>
            <geometry>
                <box size="${properties['torso']['side']['width']} ${properties['torso']['side']['length']} ${properties['torso']['side']['height']}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${properties['torso']['side']['mass']}" x="${properties['torso']['side']['width']}" y="${properties['torso']['side']['length']}" z="${properties['torso']['side']['height']}" >
            <origin xyz="0 0 ${properties['torso']['side']['height'] / 2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- Left torso side for sholder cross member -->
    <joint name="left_torso_side_joint" type="fixed">
        <origin xyz="${properties['torso']['side']['offset']} 0 0" rpy="0 0 0"/>
        <parent link="plate_link"/>
        <child link="left_side_link"/>
    </joint>

    <link name="left_side_link">
        <visual>
            <origin xyz="0 0 ${properties['torso']['side']['height'] / 2}" rpy="0 0 0"/>
            <geometry>
                <box size="${properties['torso']['side']['width']} ${properties['torso']['side']['length']} ${properties['torso']['side']['height']}"/>
            </geometry>
            <material name="silver" />
        </visual>
        <collision>
            <origin xyz="0 0 ${properties['torso']['side']['height'] / 2}" rpy="0 0 0"/>
            <geometry>
                <box size="${properties['torso']['side']['width']} ${properties['torso']['side']['length']} ${properties['torso']['side']['height']}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${properties['torso']['side']['mass']}" x="${properties['torso']['side']['width']}" y="${properties['torso']['side']['length']}" z="${properties['torso']['side']['height']}" >
            <origin xyz="0 0 ${properties['torso']['side']['height'] / 2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
    
    <!-- Shoulder cross member -->
    <joint name="cross_joint" type="fixed">
        <origin xyz="-${properties['torso']['side']['offset']} 0 ${properties['shoulder']['crossmember']['height']}" rpy="0 0 0"/>
        <parent link="plate_link"/>
        <child link="cross_link"/>
    </joint>

    <link name="cross_link">
        <visual>
            <origin xyz="${properties['shoulder']['crossmember']['length'] / 2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="${properties['shoulder']['crossmember']['diameter'] / 2}" length="${properties['shoulder']['crossmember']['length']}"/>
            </geometry>
            <material name="silver" />
        </visual>
        <collision>
           <origin xyz="${properties['shoulder']['crossmember']['length'] / 2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="${properties['shoulder']['crossmember']['diameter'] / 2}" length="${properties['shoulder']['crossmember']['length']}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${properties['shoulder']['crossmember']['mass']}" length="${properties['shoulder']['crossmember']['length']}" radius="${properties['shoulder']['crossmember']['diameter'] / 2}">
            <origin xyz="0 0 ${properties['torso']['plate_height'] / 2}" rpy="0 0 ${properties['torso']['upper_limit']}"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Primary shoulder joint & biceps -->
    <joint name="shoulder_joint" type="revolute">
        <origin xyz="${properties['torso']['side']['offset']} 0 0" rpy="0 0 0"/>
        <parent link="cross_link"/>
        <child link="biceps_link"/>
        <axis xyz="1 0 0"/>
        <limit lower="${properties['shoulder']['lower_limit']}" upper="${properties['shoulder']['upper_limit']}" velocity="100" effort="100"/> 
        <dynamics damping="10.0" friction="10.0" />
    </joint>

    <link name="biceps_link">
        <visual>
            <origin xyz="0 0 ${properties['biceps']['length'] / 2 - properties['biceps']['offset']}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${properties['biceps']['width']} ${properties['biceps']['height']} ${properties['biceps']['length']}"/>
            </geometry>
            <material name="silver" />
        </visual>
        <collision>
            <origin xyz="0 0 ${properties['biceps']['length'] / 2 - properties['biceps']['offset']}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${properties['biceps']['width']} ${properties['biceps']['height']} ${properties['biceps']['length']}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${properties['biceps']['mass']}" x="${properties['biceps']['width']}" y="${properties['biceps']['height']}" z="${properties['biceps']['length']}" >
            <origin xyz="0 0 ${properties['biceps']['length'] / 2 - properties['biceps']['offset']}" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_box>
    </link>

    <!-- Elbow and forearm -->

    <joint name="elbow_joint" type="revolute">
        <origin xyz="0 0 ${properties['biceps']['length'] - properties['biceps']['offset']}" rpy="0 0 0"/>
        <parent link="biceps_link"/>
        <child link="elbow_mimic_link"/>
        <axis xyz="1 0 0"/>
        <limit lower="${properties['forearm']['lower_limit']}" upper="${properties['forearm']['upper_limit']}" velocity="100" effort="100"/> 
        <dynamics damping="10.0" friction="10.0" />
    </joint>

    <link name="elbow_mimic_link">
        <visual name="">
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0 0 0"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0 0 0"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="1" x="0" y="0" z="0" >
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="elbow_mimic_joint" type="revolute">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="elbow_mimic_link"/>
        <child link="forearm_link"/>
        <axis xyz="1 0 0"/>
        <limit lower="${properties['forearm']['lower_limit']}" upper="${properties['forearm']['upper_limit']}" velocity="100" effort="100"/> 
        <mimic joint="shoulder_joint" multiplier="-1.0"/>
        <dynamics damping="10.0" friction="10.0" />
    </joint>

    <link name="forearm_link">
        <visual>
            <origin xyz="0 ${properties['forearm']['length']/2 - properties['forearm']['offset']} 0" rpy="${pi / 2} 0 0"/>
            <geometry>
                <box size="${properties['forearm']['width']} ${properties['forearm']['height']} ${properties['forearm']['length']}"/>
            </geometry>
            <material name="silver" />
        </visual>
        <collision>
            <origin xyz="0 ${properties['forearm']['length']/2 - properties['forearm']['offset']} 0" rpy="${pi / 2} 0 0"/>
            <geometry>
                <box size="${properties['forearm']['width']} ${properties['forearm']['height']} ${properties['forearm']['length']}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${properties['forearm']['mass']}" x="${properties['forearm']['width']}" y="${properties['forearm']['height']}" z="${properties['forearm']['length']}" >
            <origin xyz="0 ${properties['forearm']['length']/2 - properties['forearm']['offset']} 0" rpy="${pi / 2} 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- Support Arm -->
    <joint name="brace_cross_joint" type="revolute">
        <origin xyz="${properties['torso']['side']['offset'] / 2} 0 0 " rpy="0 0 0"/> 
        <parent link="cross_link"/>
        <child link="support_brace_link"/>
        <axis xyz="1 0 0"/>
        <limit lower="${properties['support_arm']['crossmember']['lower_limit']}" upper="${properties['support_arm']['crossmember']['upper_limit']}" velocity="100" effort="100"/> 
        <mimic joint="elbow_joint" multiplier="1.0" />
        <dynamics damping="10.0" friction="10.0" />
    </joint>

    <link name="support_brace_link">
        <visual>
            <origin xyz="0 -${properties['support_arm']['crossmember']['length'] / 2} 0" rpy="0 0 ${pi / 2}"/>
            <geometry>
                <box size="${properties['support_arm']['crossmember']['length']} ${properties['support_arm']['crossmember']['width']} ${properties['support_arm']['crossmember']['height']}"/>
            </geometry>
            <material name="silver" />
        </visual>
        <collision>
            <origin xyz="0 -${properties['support_arm']['crossmember']['length'] / 2} 0" rpy="0 0 ${pi / 2}"/>
            <geometry>
                <box size="${properties['support_arm']['crossmember']['length']} ${properties['support_arm']['crossmember']['width']} ${properties['support_arm']['crossmember']['height']}" />
            </geometry>
        </collision>
        <xacro:inertial_box mass="${properties['support_arm']['crossmember']['mass']}" x="${properties['support_arm']['crossmember']['width']}" y="${properties['support_arm']['crossmember']['height']}" z="${properties['support_arm']['crossmember']['length']}" >
            <origin xyz="0 -${properties['support_arm']['crossmember']['length'] / 2} 0" rpy="0 0 ${pi / 2}"/>
        </xacro:inertial_box>
    </link>

    <joint name="support_elbow_mimic_joint" type="revolute">
        <origin xyz="0 -${properties['support_arm']['crossmember']['length']} 0" rpy="0 0 0"/>
        <parent link="support_brace_link"/>
        <child link="support_mimic_link"/>
        <axis xyz="1 0 0"/>
        <limit lower="${properties['support_arm']['main']['lower_limit']}" upper="${properties['support_arm']['main']['upper_limit']}" effort="100" velocity="100"/>
        <mimic joint="elbow_joint" multiplier="-1.0" />
        <dynamics damping="10.0" friction="10.0" />
    </joint>

    <link name="support_mimic_link">
        <visual name="">
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0 0 0"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0 0 0"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="1" x="0" y="0" z="0" >
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
    
    <joint name="support_shoulder_mimic_joint" type="revolute">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="support_mimic_link"/>
        <child link="support_arm_link"/>
        <axis xyz="1 0 0"/>
        <limit lower="${properties['support_arm']['main']['lower_limit']}" upper="${properties['support_arm']['main']['upper_limit']}" effort="100" velocity="100"/>
        <mimic joint="shoulder_joint" multiplier="1.0" />
        <dynamics damping="10.0" friction="10.0" />
    </joint>

    <link name="support_arm_link">
        <visual>
            <origin xyz="0 0 ${properties['support_arm']['main']['length'] / 2}" rpy="0 0 0"/>
            <geometry>
                <box size="${properties['support_arm']['main']['width']} ${properties['support_arm']['main']['height']} ${properties['support_arm']['main']['length']}"/>
            </geometry>
            <material name="silver" />
        </visual>
        <collision>
            <origin xyz="0 0 ${properties['support_arm']['main']['length'] / 2}" rpy="0 0 0"/>
            <geometry>
                <box size="${properties['support_arm']['main']['width']} ${properties['support_arm']['main']['height']} ${properties['support_arm']['main']['length']}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${properties['support_arm']['main']['mass']}" x="${properties['support_arm']['main']['width']}" y="${properties['support_arm']['main']['height']}" z="${properties['support_arm']['main']['length']}" >
            <origin xyz="0 0 ${properties['support_arm']['main']['length'] / 2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- Include gazebo configuration to add gazebo properties and configure ros2_control -->
    <xacro:include filename="gazebo.xacro"/>
</robot>